name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Install Railway CLI
        run: |
          curl -fsSL https://cli.railway.app/install.sh | bash
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
          
      - name: Deploy to Railway
        run: |
          railway up
